export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_IS_LOADING = 'USER_IS_LOADING';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_SET_USER = 'USER_SET_USER';
export const USER_SET_TOKEN = 'USER_SET_TOKEN';
export const USER_SET_LOADING = 'USER_SET_LOADING';
export const CLEAR_ERROR = 'CLEAR_ERROR';